### ISSUE TITLE
TypeError: Cannot read property 'refIdP' of undefined 

### ISSUE THREAD

**Issue by gustawdaniel** [EclairJS/eclairjs-node#118]
After pasting example I have error:

```
/media/nvme/pro/se/local/app/node_modules/eclairjs/client/lib/utils.js:670
        if (item.refIdP) {
                 ^

TypeError: Cannot read property 'refIdP' of undefined
    at /media/nvme/pro/se/local/app/node_modules/eclairjs/client/lib/utils.js:670:18
    at Array.forEach (<anonymous>)
    at Object.Utils.wrapArray (/media/nvme/pro/se/local/app/node_modules/eclairjs/client/lib/utils.js:663:9)
    at Object.Utils.wrapBindArgs (/media/nvme/pro/se/local/app/node_modules/eclairjs/client/lib/utils.js:720:16)
    at RDD.mapToPair (/media/nvme/pro/se/local/app/node_modules/eclairjs/client/lib/rdd/RDD.js:399:21)
    at Object.<anonymous> (/media/nvme/pro/se/local/app/app.js:13:28)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
```

Node v15.8.0

**Comment by whereswaldon** [comment]
I believe that this project is completely unmaintained. The last commit was in 2016.
