### ISSUE TITLE
Filter Anonymous Function Scope Bug

### ISSUE THREAD

**Issue by whereswaldon** [EclairJS/eclairjs-node#98]
When you're attempting to filter options from an RDD, the filter's anonymous function silently fails when trying to access variables outside of its own scope.

Here is a simple (working) spark code snippet in python with its equivalent (not working) code in javascript:
```python
rdd = sc.parallelize(range(10))
nums = [1,4,2,6,7]
rdd = rdd.filter(lambda row: row in nums)
rdd.collect()
```

```javascript
var rdd = context.parallelize([0,1,2,3,4,5,6,7,8,9]);
var nums = [1,4,2,6,7];
rdd = rdd.filter(function(element){
    return nums.indexOf(element) > -1;
});

rdd.collect().then(function(data){
	console.log(data);
}, function(error) {
	console.error(error);
});
```

We expect to see `[1,2,4,6,7]`, but we get

```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 9 in stage 470.0 failed 1 times, most recent failure: Lost task 9.0 in stage 470.0 (TID 1853, localhost): javax.script.ScriptException: ReferenceError: "nums" is not defined in jar:file:/opt/nashorn/lib/eclairjs.jar!/eclairjs/EclairJS_Globals.js at line number 37 at column number 8
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:467)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:389)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
	at org.eclairjs.nashorn.JSFunction.call(JSFunction.java:48)
	at org.apache.spark.api.java.JavaRDD$$anonfun$filter$1.apply(JavaRDD.scala:78)
	at org.apache.spark.api.java.JavaRDD$$anonfun$filter$1.apply(JavaRDD.scala:78)
	at scala.collection.Iterator$$anon$14.hasNext(Iterator.scala:390)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
	at scala.collection.AbstractIterator.to(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1157)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:927)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:927)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: jar:file:/opt/nashorn/lib/eclairjs.jar!/eclairjs/EclairJS_Globals.js:37:8 ReferenceError: "nums" is not defined
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319)
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291)
	at jdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:1428)
	at jdk.nashorn.internal.scripts.Script$Recompilation$412$18A$EclairJS_Globals.L:1(jar:file:/opt/nashorn/lib/eclairjs.jar!/eclairjs/EclairJS_Globals.js#22:13<eval>:2)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:625)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.internal.objects.NativeFunction.apply(NativeFunction.java:104)
	at jdk.nashorn.internal.scripts.Script$Recompilation$179$EclairJS_Globals.Utils_invoke(jar:file:/opt/nashorn/lib/eclairjs.jar!/eclairjs/EclairJS_Globals.js:32)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:614)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:383)
	... 26 more

Driver stacktrace:
jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:397)
jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:446)
jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:403)
jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
org.eclairjs.nashorn.JavascriptInterpreter$$anonfun$2$$anonfun$apply$1.apply(JavascriptInterpreter.scala:187)
org.eclairjs.nashorn.JavascriptInterpreter$$anonfun$2$$anonfun$apply$1.apply(JavascriptInterpreter.scala:187)
org.apache.toree.global.StreamState$.withStreams(StreamState.scala:81)
org.eclairjs.nashorn.JavascriptInterpreter$$anonfun$2.apply(JavascriptInterpreter.scala:185)
org.eclairjs.nashorn.JavascriptInterpreter$$anonfun$2.apply(JavascriptInterpreter.scala:185)
scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) 
```

**Comment by doronrosenberg** [comment]
https://github.com/EclairJS/eclairjs-node/wiki/Working-With-Lambda-Functions#passing-variables-to-lambdas

Your code would look like this:

```
var rdd = context.parallelize([0,1,2,3,4,5,6,7,8,9]);
var nums = [1,4,2,6,7];
rdd = rdd.filter(function(element, myNums){
    return myNums.indexOf(element) > -1;
}, [nums]);

rdd.collect().then(function(data){
    console.log(data);
}, function(error) {
    console.error(error);
});
```
